version: '3.5'
services:
  db: 
    container_name: db
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    image: postgres:14.15-alpine

